import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    cameraWrapper: {
        flex: 1,
        backgroundColor: '#000',
        borderRadius: 25,
        overflow: 'hidden',
    },
    cameraContainer: {
        flex: 1,
        position: 'relative',
    },
    camera: {
        flex: 1,
        borderRadius: 25,
    },
    cameraOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        pointerEvents: 'none',
    },
    iphoneFocusIndicator: {
        position: 'absolute',
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    iphoneFocusBox: {
        width: 60,
        height: 60,
        position: 'relative',
    },
    iphoneFocusCornerTL: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 12,
        height: 12,
        borderTopWidth: 1.5,
        borderLeftWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    iphoneFocusCornerTR: {
        position: 'absolute',
        top: 0,
        right: 0,
        width: 12,
        height: 12,
        borderTopWidth: 1.5,
        borderRightWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    iphoneFocusCornerBL: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        width: 12,
        height: 12,
        borderBottomWidth: 1.5,
        borderLeftWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    iphoneFocusCornerBR: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 12,
        height: 12,
        borderBottomWidth: 1.5,
        borderRightWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.9)',
    },
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#000',
        padding: 20,
    },
    permissionText: {
        color: 'white',
        fontSize: 18,
        textAlign: 'center',
        marginBottom: 20,
        fontWeight: '600',
    },
    permissionButton: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 30,
        paddingVertical: 15,
        borderRadius: 30,
    },
    permissionButtonText: {
        color: '#000',
        fontSize: 16,
        fontWeight: '700'
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center'
    },
    loadingText: {
        color: 'white',
        fontSize: 18,
        fontWeight: '600'
    },
    tabContainer: {
        position: 'absolute',
        bottom: 1,
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 100,
    },
    tabButton: {
        paddingHorizontal: 15,
        paddingVertical: 8,
    },
    tabText: {
        fontSize: 18,
        color: 'white',
        opacity: 0.6,
        fontWeight: '500',
    },
    tabTextSelected: {
        opacity: 1,
        fontWeight: 'bold',
        fontSize: 20,
    },
    tabSeparator: {
        fontSize: 18,
        color: 'rgba(255, 255, 255, 0.4)',
    },
    rightControls: {
        position: 'absolute',
        top: 10,
        right: 5,
        flexDirection: 'column',
        alignItems: 'flex-end',
        zIndex: 100,
    },
    rightControlsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        minWidth: 130, // Adjust as needed for your label+icon widths
        marginBottom: 10,
    },
    sideButton: {
        padding: 10,
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
    },
    folderIconButton: {
        padding: 10,
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconLabel: {
        color: 'white',
        fontSize: 15,
        marginRight: 8,
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    galleryButton: {
        position: 'absolute',
        bottom: 14,
        left: 16,
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        borderRadius: 7,
        zIndex: 105,
    },
    zoomIndicator: {
        position: 'absolute',
        bottom: 24,
        left: 16,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    zoomText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '700'
    },
    recordingIndicator: {
        position: 'absolute',
        top: 5,
        alignSelf: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
    },
    recordingDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: 'white',
        marginRight: 8
    },
    recordingText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '700'
    },
});
